POST https://8080-cabreraluca-atividadeap-jaf60tllrj5.ws-us110.gitpod.io/compromissos
Content-Type: application/json

{
    "descricao" : "Palestra Fatec",
    "dataInicio" : "26/03",
    "dataFim" : "28/03",
    "horaInicio" : "8h00",
    "horaFim" : "10h00",
}