POST https://8080-cabreraluca-atividadeap-1f15fukp68s.ws-us110.gitpod.io/compromissos
Content-Type: application/json

{
    "descricao" : "Exemplo3",
    "dataHoraInicial" : "02/04/2024 8:00:00",
    "dataHoraFinal" : "03/04/2024 10:00:00"
}